function [ flag ] = lfpprepf_Takeuchi3_with1A1D_500Hz( datfilenamebase, srLFP, nChannels)
%
% [ flag ] = lfpprepf_Takeuchi3_with1A1D_500Hz( datfilenamebase, srLFP, nChannels)
%
% This function DC removes, extracts dig and stim waves from the
% original dat file
%
% INPUTS:
%   datfilenamebase: base name of the .dat file to be read
%   nChannels: total number of recording channels
% 
% Copyright (C) Yuichi Takeuchi 2017, 2018
%

flag = 0;

% Resampling dat file
% none

% Extract the digital channel
disp('extracting a digital channel...')
apf_ExtractChannels([datfilenamebase '.dat'],...
                    [datfilenamebase '_dig.dat'],...
                    [32],...
                    nChannels);
disp('done.')

% Extract the stim waveform channel
disp('extracting analog input channels...')
apf_ExtractChannels([datfilenamebase '.dat'],...
                    [datfilenamebase '_1_adc.dat'],...
                    [31],...
                    nChannels);
disp('done.')

channelvector = [2 1 3 ...
                5 6 4 ...
                8 7 9 ...
                11 12 10 ...
                14 13 15 ...
                17 16 18 ...
                20 21 19 ...
                23 22 24 ...
                26 25 27 ...
                29 30 28];

% Reorganize channels from .dat file without stim and digital input channels
disp('headstage inputs...')
apf_ExtractChannels([datfilenamebase '.dat'],...
                    [datfilenamebase '_reorg.dat'],...
                    channelvector,...
                    nChannels);
disp('done.')

% Remove DC from analog and headstage input channels file
disp('removing DC shifts from analog channels...')
% [returnVar,msg] = RemoveDCfromDat([datfilenamebase '_stim.dat'], 1);
[returnVar,msg] = RemoveDCfromDat([datfilenamebase '_reorg.dat'], 30);
[returnVar,msg] = RemoveDCfromDat([datfilenamebase '_1_adc.dat'], 1);
disp('done.')

% Low-pass filtering LFP data
disp('Low-pass filtering...')
filtf_LowPassButter1([datfilenamebase '_reorg.dat'],...
                [datfilenamebase '_LFP_reorgtemp.dat'],...
                30,...
                floor(srLFP)/2,...
                3,...
                srLFP);
% or filtf_LowPassButter2 for previous Matlab version
disp('Low-pass filtering done.')

% High-pass filtering LFP data
disp('High-pass filtering...')
filtf_HighPassButter1([datfilenamebase '_LFP_reorgtemp.dat'],...
                [datfilenamebase '_LFP_reorg.dat'],...
                30,...
                0.3,...
                3,...
                srLFP);
% or filtf_LowPassButter2 for previous Matlab version
disp('High-pass filtering done.')
copyfile([datfilenamebase '_LFP_reorg.dat'], [datfilenamebase '_1_LFP_reorg.dat'])

% deleting unnecessary files
delete([datfilenamebase  '_reorg.dat'])
delete([datfilenamebase '_LFP_reorgtemp.dat'])
delete([datfilenamebase '_LFP_reorg.dat'])

flag = 1;