function [ destStruct ] = stats_BuildStructTTest2( srcVec1, srcVec2 )
%
% [ destStruct ] = stats_BuildStructTTest2( srcVec1, srcVec2 )
%   
% Copyright (C) Yuichi Takeuchi 2017
%

[h,p,ci,stats] = ttest2(srcVec1, srcVec2);
destStruct = struct(...
    'h', h,...
    'p', p,...
    'ci', ci,...
    'stats', stats...
    );
end

